# Generated by Django 3.0.7 on 2020-06-08 08:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=10, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=15, verbose_name='Middle Name')),
                ('door', models.IntegerField(verbose_name='Door')),
                ('method', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(verbose_name='Method'), size=3)),
                ('pin', models.IntegerField(verbose_name='PIN')),
                ('fingerprintID', models.IntegerField(verbose_name='Fingerprint ID')),
                ('rfid', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='RFID'), size=10)),
                ('start_time', models.IntegerField(verbose_name='Start Time')),
                ('end_time', models.IntegerField(verbose_name='End Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
