# Generated by Django 3.0.7 on 2020-06-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='door',
        ),
        migrations.RemoveField(
            model_name='database',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='database',
            name='fingerprintID',
        ),
        migrations.RemoveField(
            model_name='database',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='database',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='database',
            name='method',
        ),
        migrations.RemoveField(
            model_name='database',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='database',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='database',
            name='rfid',
        ),
        migrations.RemoveField(
            model_name='database',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='database',
            name='user',
        ),
        migrations.AddField(
            model_name='database',
            name='Door',
            field=models.IntegerField(default=0, verbose_name='Door'),
        ),
        migrations.AddField(
            model_name='database',
            name='EndTime',
            field=models.IntegerField(null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='database',
            name='FingerprintID',
            field=models.IntegerField(null=True, verbose_name='Fingerprint ID'),
        ),
        migrations.AddField(
            model_name='database',
            name='FirstName',
            field=models.CharField(default='Unset', max_length=10, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='database',
            name='LastName',
            field=models.CharField(default='Unset', max_length=10, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='database',
            name='MethodFPID',
            field=models.BooleanField(default=False, verbose_name='Method FP'),
        ),
        migrations.AddField(
            model_name='database',
            name='MethodPIN',
            field=models.BooleanField(default=False, verbose_name='Method PIN'),
        ),
        migrations.AddField(
            model_name='database',
            name='MethodRFID',
            field=models.BooleanField(default=False, verbose_name='Method RFID'),
        ),
        migrations.AddField(
            model_name='database',
            name='MiddleName',
            field=models.CharField(default='Unset', max_length=10, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='database',
            name='PIN',
            field=models.IntegerField(default=0, verbose_name='PIN'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID1',
            field=models.IntegerField(default=0, verbose_name='RFID 1'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID10',
            field=models.IntegerField(default=0, verbose_name='RFID 10'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID2',
            field=models.IntegerField(default=0, verbose_name='RFID 2'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID3',
            field=models.IntegerField(default=0, verbose_name='RFID 3'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID4',
            field=models.IntegerField(default=0, verbose_name='RFID 4'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID5',
            field=models.IntegerField(default=0, verbose_name='RFID 5'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID6',
            field=models.IntegerField(default=0, verbose_name='RFID 6'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID7',
            field=models.IntegerField(default=0, verbose_name='RFID 7'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID8',
            field=models.IntegerField(default=0, verbose_name='RFID 8'),
        ),
        migrations.AddField(
            model_name='database',
            name='RFID9',
            field=models.IntegerField(default=0, verbose_name='RFID 9'),
        ),
        migrations.AddField(
            model_name='database',
            name='StartTime',
            field=models.IntegerField(null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='database',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
