# Generated by Django 3.0.7 on 2020-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200608_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'SUCCESSFUL_AUTH'), (1, 'OPEN'), (2, 'FALL_FIRST_AUTH'), (3, 'FALL_SEC_AUTH')], verbose_name='Type of log entry')),
                ('time', models.IntegerField(null=True, verbose_name='Time')),
                ('day', models.IntegerField(null=True, verbose_name='Day')),
                ('month', models.IntegerField(null=True, verbose_name='Month')),
                ('year', models.IntegerField(null=True, verbose_name='Year')),
                ('door', models.IntegerField(default=-1, verbose_name='Door')),
                ('userID', models.IntegerField(default=-1, verbose_name='User ID')),
            ],
        ),
    ]
