# Generated by Django 3.0.7 on 2020-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200609_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='hour',
            field=models.IntegerField(null=True, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='type',
            field=models.IntegerField(choices=[(0, 'SUCCESSFUL_AUTH'), (1, 'OPEN'), (2, 'FALL_FIRST_AUTH'), (3, 'FALL_SEC_AUTH'), (4, 'FALL_BY_TIME')], verbose_name='Type of log entry'),
        ),
    ]
